// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutils

import (
	"context"

	"github.com/loopinnovates/wallet-transfer-assignment/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITransferRepository creates a new instance of MockITransferRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransferRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransferRepository {
	mock := &MockITransferRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITransferRepository is an autogenerated mock type for the ITransferRepository type
type MockITransferRepository struct {
	mock.Mock
}

type MockITransferRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransferRepository) EXPECT() *MockITransferRepository_Expecter {
	return &MockITransferRepository_Expecter{mock: &_m.Mock}
}

// ExecuteTransfer provides a mock function for the type MockITransferRepository
func (_mock *MockITransferRepository) ExecuteTransfer(ctx context.Context, idempotencyKey string, fromWalletID string, toWalletID string, amount float64, timestamp int64) (*domain.Transfer, error) {
	ret := _mock.Called(ctx, idempotencyKey, fromWalletID, toWalletID, amount, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteTransfer")
	}

	var r0 *domain.Transfer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64, int64) (*domain.Transfer, error)); ok {
		return returnFunc(ctx, idempotencyKey, fromWalletID, toWalletID, amount, timestamp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, float64, int64) *domain.Transfer); ok {
		r0 = returnFunc(ctx, idempotencyKey, fromWalletID, toWalletID, amount, timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transfer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, float64, int64) error); ok {
		r1 = returnFunc(ctx, idempotencyKey, fromWalletID, toWalletID, amount, timestamp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransferRepository_ExecuteTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteTransfer'
type MockITransferRepository_ExecuteTransfer_Call struct {
	*mock.Call
}

// ExecuteTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - idempotencyKey string
//   - fromWalletID string
//   - toWalletID string
//   - amount float64
//   - timestamp int64
func (_e *MockITransferRepository_Expecter) ExecuteTransfer(ctx any, idempotencyKey any, fromWalletID any, toWalletID any, amount any, timestamp any) *MockITransferRepository_ExecuteTransfer_Call {
	return &MockITransferRepository_ExecuteTransfer_Call{Call: _e.mock.On("ExecuteTransfer", ctx, idempotencyKey, fromWalletID, toWalletID, amount, timestamp)}
}

func (_c *MockITransferRepository_ExecuteTransfer_Call) Run(run func(ctx context.Context, idempotencyKey string, fromWalletID string, toWalletID string, amount float64, timestamp int64)) *MockITransferRepository_ExecuteTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 float64
		if args[4] != nil {
			arg4 = args[4].(float64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockITransferRepository_ExecuteTransfer_Call) Return(transfer *domain.Transfer, err error) *MockITransferRepository_ExecuteTransfer_Call {
	_c.Call.Return(transfer, err)
	return _c
}

func (_c *MockITransferRepository_ExecuteTransfer_Call) RunAndReturn(run func(ctx context.Context, idempotencyKey string, fromWalletID string, toWalletID string, amount float64, timestamp int64) (*domain.Transfer, error)) *MockITransferRepository_ExecuteTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdempotencyKey provides a mock function for the type MockITransferRepository
func (_mock *MockITransferRepository) GetByIdempotencyKey(ctx context.Context, key string) (*domain.Transfer, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *domain.Transfer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Transfer, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Transfer); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transfer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransferRepository_GetByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdempotencyKey'
type MockITransferRepository_GetByIdempotencyKey_Call struct {
	*mock.Call
}

// GetByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockITransferRepository_Expecter) GetByIdempotencyKey(ctx any, key any) *MockITransferRepository_GetByIdempotencyKey_Call {
	return &MockITransferRepository_GetByIdempotencyKey_Call{Call: _e.mock.On("GetByIdempotencyKey", ctx, key)}
}

func (_c *MockITransferRepository_GetByIdempotencyKey_Call) Run(run func(ctx context.Context, key string)) *MockITransferRepository_GetByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransferRepository_GetByIdempotencyKey_Call) Return(transfer *domain.Transfer, err error) *MockITransferRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(transfer, err)
	return _c
}

func (_c *MockITransferRepository_GetByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.Transfer, error)) *MockITransferRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}
