// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutils

import (
	"context"

	"github.com/loopinnovates/wallet-transfer-assignment/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletRepository creates a new instance of MockWalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletRepository {
	mock := &MockWalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletRepository is an autogenerated mock type for the WalletRepository type
type MockWalletRepository struct {
	mock.Mock
}

type MockWalletRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletRepository) EXPECT() *MockWalletRepository_Expecter {
	return &MockWalletRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockWalletRepository
func (_mock *MockWalletRepository) GetByID(ctx context.Context, id string) (*domain.Wallet, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Wallet, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Wallet); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Wallet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWalletRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockWalletRepository_Expecter) GetByID(ctx any, id any) *MockWalletRepository_GetByID_Call {
	return &MockWalletRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWalletRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockWalletRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletRepository_GetByID_Call) Return(wallet *domain.Wallet, err error) *MockWalletRepository_GetByID_Call {
	_c.Call.Return(wallet, err)
	return _c
}

func (_c *MockWalletRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Wallet, error)) *MockWalletRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
