// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type LedgerEntry struct {
	ID         string    `json:"id"`
	TransferID string    `json:"transfer_id"`
	WalletID   string    `json:"wallet_id"`
	EntryType  string    `json:"entry_type"`
	Amount     float64   `json:"amount"`
	CreatedAt  time.Time `json:"created_at"`
}

type Transfer struct {
	ID             string         `json:"id"`
	IdempotencyKey string         `json:"idempotency_key"`
	FromWalletID   string         `json:"from_wallet_id"`
	ToWalletID     string         `json:"to_wallet_id"`
	Amount         float64        `json:"amount"`
	Status         string         `json:"status"`
	FailureReason  sql.NullString `json:"failure_reason"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Wallet struct {
	ID        string    `json:"id"`
	OwnerName string    `json:"owner_name"`
	Balance   float64   `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
