// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreditWallet(ctx context.Context, arg CreditWalletParams) error
	DebitWallet(ctx context.Context, arg DebitWalletParams) error
	GetTransferByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transfer, error)
	GetWalletBalance(ctx context.Context, id string) (float64, error)
	GetWalletByID(ctx context.Context, id string) (Wallet, error)
	InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error
	InsertTransfer(ctx context.Context, arg InsertTransferParams) (Transfer, error)
	LockWalletByID(ctx context.Context, id string) (string, error)
}

var _ Querier = (*Queries)(nil)
