// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getTransferByIdempotencyKey = `-- name: GetTransferByIdempotencyKey :one
SELECT id, idempotency_key, from_wallet_id, to_wallet_id, amount, status, failure_reason, created_at, updated_at
FROM transfers
WHERE idempotency_key = $1
`

func (q *Queries) GetTransferByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferByIdempotencyKey, idempotencyKey)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (transfer_id, wallet_id, entry_type, amount)
VALUES ($1, $2, $3, $4)
`

type InsertLedgerEntryParams struct {
	TransferID string  `json:"transfer_id"`
	WalletID   string  `json:"wallet_id"`
	EntryType  string  `json:"entry_type"`
	Amount     float64 `json:"amount"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertLedgerEntry,
		arg.TransferID,
		arg.WalletID,
		arg.EntryType,
		arg.Amount,
	)
	return err
}

const insertPendingTransfer = `-- name: InsertPendingTransfer :one
INSERT INTO transfers (idempotency_key, from_wallet_id, to_wallet_id, amount, status)
VALUES ($1, $2, $3, $4, 'PENDING')
RETURNING id, idempotency_key, from_wallet_id, to_wallet_id, amount, status, failure_reason, created_at, updated_at
`

type InsertPendingTransferParams struct {
	IdempotencyKey string  `json:"idempotency_key"`
	FromWalletID   string  `json:"from_wallet_id"`
	ToWalletID     string  `json:"to_wallet_id"`
	Amount         float64 `json:"amount"`
}

func (q *Queries) InsertPendingTransfer(ctx context.Context, arg InsertPendingTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, insertPendingTransfer,
		arg.IdempotencyKey,
		arg.FromWalletID,
		arg.ToWalletID,
		arg.Amount,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTransferFailed = `-- name: MarkTransferFailed :one
UPDATE transfers
SET status = 'FAILED', failure_reason = $2, updated_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, idempotency_key, from_wallet_id, to_wallet_id, amount, status, failure_reason, created_at, updated_at
`

type MarkTransferFailedParams struct {
	ID            string         `json:"id"`
	FailureReason sql.NullString `json:"failure_reason"`
}

func (q *Queries) MarkTransferFailed(ctx context.Context, arg MarkTransferFailedParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, markTransferFailed, arg.ID, arg.FailureReason)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTransferProcessed = `-- name: MarkTransferProcessed :one
UPDATE transfers
SET status = 'PROCESSED', updated_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, idempotency_key, from_wallet_id, to_wallet_id, amount, status, failure_reason, created_at, updated_at
`

func (q *Queries) MarkTransferProcessed(ctx context.Context, id string) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, markTransferProcessed, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.FromWalletID,
		&i.ToWalletID,
		&i.Amount,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
