// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlcgen

import (
	"context"
)

const creditWallet = `-- name: CreditWallet :exec
UPDATE wallets SET balance = balance + $1, updated_at = now() WHERE id = $2
`

type CreditWalletParams struct {
	Balance float64 `json:"balance"`
	ID      string  `json:"id"`
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) error {
	_, err := q.db.ExecContext(ctx, creditWallet, arg.Balance, arg.ID)
	return err
}

const debitWallet = `-- name: DebitWallet :exec
UPDATE wallets SET balance = balance - $1, updated_at = now() WHERE id = $2
`

type DebitWalletParams struct {
	Balance float64 `json:"balance"`
	ID      string  `json:"id"`
}

func (q *Queries) DebitWallet(ctx context.Context, arg DebitWalletParams) error {
	_, err := q.db.ExecContext(ctx, debitWallet, arg.Balance, arg.ID)
	return err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT balance FROM wallets WHERE id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, id string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getWalletBalance, id)
	var balance float64
	err := row.Scan(&balance)
	return balance, err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, owner_name, balance, created_at, updated_at
FROM wallets
WHERE id = $1
`

func (q *Queries) GetWalletByID(ctx context.Context, id string) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.OwnerName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWalletByID = `-- name: LockWalletByID :one
SELECT id FROM wallets WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockWalletByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockWalletByID, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
